 
 - name: Ensure the WAN interface is enabled
      pfsense_interface:
        name: 'wan'
        enabled: yes
        pfSense:
          hostname: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"